spring.datasource.url=jdbc:mysql://employeedb.c0xkqewi8obz.us-east-1.rds.amazonaws.com:3306/employeeDB
spring.datasource.username=root
spring.datasource.password=root1234
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081
spring.jpa.show-sql=true